language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-pxa-frontend' ]; then cd .. && eval "mv $currentfolder generator-pxa-frontend" && cd generator-pxa-frontend; fi

