#!/bin/bash

DIRECTORY="<%= (dirr) %>"
FDIRECTORY="<%= (dirr) %>/typo3conf/ext"
GIT="<%= (gitt) %>"

if [ ! -d "$DIRECTORY" ]; then
  git clone $GIT
fi

if [ ! -d "$FDIRECTORY" ]; then
    grunt shared_start
else
    grunt start
fi
