#!/bin/bash
SETCOLOR_GREEN="echo -en \\033[1;32m"
SETCOLOR_RED="echo -en \\033[1;31m"
SETCOLOR_CYAN="echo -en \\033[1;36m"
SETCOLOR_BLUE="echo -en \\033[1;34m"
COLOR_RESET="echo -en \\033[0m"

$SETCOLOR_CYAN
echo "PRESS Ctrl+C TO STOP THIS TASK"
trap "echo ." SIGINT SIGTERM
$COLOR_RESET
repo
grunt start
grunt end
$SETCOLOR_GREEN
echo
echo "Now you can commit your changes or update pxa modules"
